# 🎮 Pandas Practice — 06: Combining DataFrames
**Dataset:** Multiple related video game tables you'll concat and merge together.

---
## Setup — run this cell first!
This notebook creates several small DataFrames that simulate a real database split across tables.

In [44]:
import numpy as np
import pandas as pd

# --- Table 1: Game catalog (basic info)
games = pd.DataFrame({
    'game_id':   [1, 2, 3, 4, 5, 6, 7, 8],
    'title':     ['Halo 3', 'FIFA 14', 'GTA V', 'Minecraft', 'Mario Kart Wii',
                  'Tetris', 'God of War', 'The Sims 3'],
    'genre':     ['Shooter', 'Sports', 'Action', 'Misc', 'Racing',
                  'Puzzle', 'Action', 'Simulation'],
    'year':      [2007, 2013, 2013, 2013, 2008, 1989, 2005, 2009]
})

# --- Table 2: Sales figures
sales = pd.DataFrame({
    'game_id':    [1, 2, 3, 4, 5, 7, 8, 9],   # note: 6 (Tetris) missing, 9 is unknown
    'na_sales':   [7.22, 2.04, 7.01, 7.26, 15.85, 2.56, 4.13, 1.50],
    'eu_sales':   [3.93, 8.74, 9.27, 4.18, 12.88, 2.12, 4.73, 0.80],
    'global_sales':[12.32, 12.2, 20.32, 13.0, 35.82, 5.17, 10.2, 2.80]
})

# --- Table 3: Critic scores
scores = pd.DataFrame({
    'game_id':      [1, 3, 4, 5, 6, 7],
    'critic_score': [94, 97, 82, 82, None, 94],
    'user_score':   [8.3, 8.2, 7.9, 8.9, None, 8.7]
})

# --- Table 4: Publisher info (for merging on name)
publishers_a = pd.DataFrame({
    'title':      ['Halo 3', 'Minecraft', 'The Sims 3'],
    'publisher':  ['Microsoft', 'Microsoft', 'EA']
})
publishers_b = pd.DataFrame({
    'title':      ['FIFA 14', 'GTA V', 'Mario Kart Wii'],
    'publisher':  ['EA Sports', 'Take-Two', 'Nintendo']
})

print("Tables loaded!")
print("games:", games.shape, "| sales:", sales.shape, "| scores:", scores.shape)

Tables loaded!
games: (8, 4) | sales: (8, 4) | scores: (6, 3)

---
## Section 1 — `pd.concat()`

### Exercise 1.1 — Stack rows (axis=0)
`publishers_a` and `publishers_b` have the same columns.
Concatenate them **vertically** into a single `publishers` DataFrame.
Reset the index afterward.

In [3]:
# Your code here
publishers = pd.concat([publishers_a,publishers_b],axis=0)
publishers

            title  publisher
0          Halo 3  Microsoft
1       Minecraft  Microsoft
2      The Sims 3         EA
0         FIFA 14  EA Sports
1           GTA V   Take-Two
2  Mario Kart Wii   Nintendo

### Exercise 1.2 — Concat with mismatched columns
Create these two DataFrames and concatenate them along `axis=0`.
What happens to the missing columns? How can you fill those NaNs with `0`?
```python
q1 = pd.DataFrame({'Platform': ['PS5', 'Xbox'], 'Q1_Sales': [4.2, 3.1]})
q2 = pd.DataFrame({'Platform': ['PS5', 'Switch'], 'Q2_Sales': [5.0, 6.3]})
```

In [4]:
q1 = pd.DataFrame({'Platform': ['PS5', 'Xbox'],    'Q1_Sales': [4.2, 3.1]})
q2 = pd.DataFrame({'Platform': ['PS5', 'Switch'], 'Q2_Sales': [5.0, 6.3]})
# Your code here

In [6]:
q1_q2 = pd.concat([q1,q2],axis=0)
q1_q2

  Platform  Q1_Sales  Q2_Sales
0      PS5       4.2       NaN
1     Xbox       3.1       NaN
0      PS5       NaN       5.0
1   Switch       NaN       6.3

In [ ]:
#Missing data gets replaced by a NaN value

### Exercise 1.3 — Concat columns (axis=1)
Concatenate `games` and `sales` side by side (`axis=1`).
What problem appears? How would you avoid it in a real workflow?
*(Write your answer as a comment)*

In [ ]:
# Your code here
pd.concat([games,sales],axis=1)
#Problem is that in second DataFrame theres no informatio for game 6

,game_id,title,genre,year,game_id,na_sales,eu_sales,global_sales
0,1,Halo 3,Shooter,2007,1,7.22,3.93,12.32
1,2,FIFA 14,Sports,2013,2,2.04,8.74,12.20
2,3,GTA V,Action,2013,3,7.01,9.27,20.32
3,4,Minecraft,Misc,2013,4,7.26,4.18,13.00
4,5,Mario Kart Wii,Racing,2008,5,15.85,12.88,35.82
5,6,Tetris,Puzzle,1989,7,2.56,2.12,5.17
6,7,God of War,Action,2005,8,4.13,4.73,10.20
7,8,The Sims 3,Simulation,2009,9,1.50,0.80,2.80

---
## Section 2 — `pd.merge()` join types

### Exercise 2.1 — Inner join
Merge `games` and `sales` on `game_id` using an **inner join**.
How many rows does the result have, and which games were dropped?

In [ ]:
# Your code here
display(games)
display(sales)
display(pd.merge(games,sales,how='inner',on='game_id'))

#Game number 6 and 9 gets dropped because is not shared on both tables

   game_id           title       genre  year
0        1          Halo 3     Shooter  2007
1        2         FIFA 14      Sports  2013
2        3           GTA V      Action  2013
3        4       Minecraft        Misc  2013
4        5  Mario Kart Wii      Racing  2008
5        6          Tetris      Puzzle  1989
6        7      God of War      Action  2005
7        8      The Sims 3  Simulation  2009

   game_id  na_sales  eu_sales  global_sales
0        1      7.22      3.93         12.32
1        2      2.04      8.74         12.20
2        3      7.01      9.27         20.32
3        4      7.26      4.18         13.00
4        5     15.85     12.88         35.82
5        7      2.56      2.12          5.17
6        8      4.13      4.73         10.20
7        9      1.50      0.80          2.80

   game_id           title       genre  year  na_sales  eu_sales  global_sales
0        1          Halo 3     Shooter  2007      7.22      3.93         12.32
1        2         FIFA 14      Sports  2013      2.04      8.74         12.20
2        3           GTA V      Action  2013      7.01      9.27         20.32
3        4       Minecraft        Misc  2013      7.26      4.18         13.00
4        5  Mario Kart Wii      Racing  2008     15.85     12.88         35.82
5        7      God of War      Action  2005      2.56      2.12          5.17
6        8      The Sims 3  Simulation  2009      4.13      4.73         10.20

### Exercise 2.2 — Left join
Merge `games` and `sales` on `game_id` using a **left join**.
Which game now shows NaN in the sales columns? Why?

In [ ]:
# Your code here
display(games)
display(sales)
display(pd.merge(games,sales,how='left',on='game_id'))

#Only number 9 gets dropped because all the games from table games are included

   game_id           title       genre  year
0        1          Halo 3     Shooter  2007
1        2         FIFA 14      Sports  2013
2        3           GTA V      Action  2013
3        4       Minecraft        Misc  2013
4        5  Mario Kart Wii      Racing  2008
5        6          Tetris      Puzzle  1989
6        7      God of War      Action  2005
7        8      The Sims 3  Simulation  2009

   game_id  na_sales  eu_sales  global_sales
0        1      7.22      3.93         12.32
1        2      2.04      8.74         12.20
2        3      7.01      9.27         20.32
3        4      7.26      4.18         13.00
4        5     15.85     12.88         35.82
5        7      2.56      2.12          5.17
6        8      4.13      4.73         10.20
7        9      1.50      0.80          2.80

   game_id           title       genre  year  na_sales  eu_sales  global_sales
0        1          Halo 3     Shooter  2007      7.22      3.93         12.32
1        2         FIFA 14      Sports  2013      2.04      8.74         12.20
2        3           GTA V      Action  2013      7.01      9.27         20.32
3        4       Minecraft        Misc  2013      7.26      4.18         13.00
4        5  Mario Kart Wii      Racing  2008     15.85     12.88         35.82
5        6          Tetris      Puzzle  1989       NaN       NaN           NaN
6        7      God of War      Action  2005      2.56      2.12          5.17
7        8      The Sims 3  Simulation  2009      4.13      4.73         10.20

### Exercise 2.3 — Right join
Merge `games` and `sales` on `game_id` using a **right join**.
What appears in the `title` column for `game_id = 9`? What does this tell you?

In [ ]:
# Your code here
display(games)
display(sales)
display(pd.merge(games,sales,how='right',on='game_id'))

#Game number 6 get dropped because it doesn't exists on Table 2, 
# however, game 9 does appear but with some Null values, this because
# that information don't exists neither

   game_id           title       genre  year
0        1          Halo 3     Shooter  2007
1        2         FIFA 14      Sports  2013
2        3           GTA V      Action  2013
3        4       Minecraft        Misc  2013
4        5  Mario Kart Wii      Racing  2008
5        6          Tetris      Puzzle  1989
6        7      God of War      Action  2005
7        8      The Sims 3  Simulation  2009

   game_id  na_sales  eu_sales  global_sales
0        1      7.22      3.93         12.32
1        2      2.04      8.74         12.20
2        3      7.01      9.27         20.32
3        4      7.26      4.18         13.00
4        5     15.85     12.88         35.82
5        7      2.56      2.12          5.17
6        8      4.13      4.73         10.20
7        9      1.50      0.80          2.80

,game_id,title,genre,year,na_sales,eu_sales,global_sales
0,1,Halo 3,Shooter,2007.0,7.22,3.93,12.32
1,2,FIFA 14,Sports,2013.0,2.04,8.74,12.20
2,3,GTA V,Action,2013.0,7.01,9.27,20.32
3,4,Minecraft,Misc,2013.0,7.26,4.18,13.00
4,5,Mario Kart Wii,Racing,2008.0,15.85,12.88,35.82
5,7,God of War,Action,2005.0,2.56,2.12,5.17
6,8,The Sims 3,Simulation,2009.0,4.13,4.73,10.20
7,9,NaN,NaN,NaN,1.50,0.80,2.80

### Exercise 2.4 — Outer join
Merge `games` and `sales` using an **outer join**.
Confirm that this is the union of left + right joins — count rows and compare.

In [ ]:
# Your code here
display(games)
display(sales)
display(pd.merge(games,sales,how='outer',on='game_id'))

#Both game 6 and 9 exists but with some NaN values

   game_id           title       genre  year
0        1          Halo 3     Shooter  2007
1        2         FIFA 14      Sports  2013
2        3           GTA V      Action  2013
3        4       Minecraft        Misc  2013
4        5  Mario Kart Wii      Racing  2008
5        6          Tetris      Puzzle  1989
6        7      God of War      Action  2005
7        8      The Sims 3  Simulation  2009

   game_id  na_sales  eu_sales  global_sales
0        1      7.22      3.93         12.32
1        2      2.04      8.74         12.20
2        3      7.01      9.27         20.32
3        4      7.26      4.18         13.00
4        5     15.85     12.88         35.82
5        7      2.56      2.12          5.17
6        8      4.13      4.73         10.20
7        9      1.50      0.80          2.80

,game_id,title,genre,year,na_sales,eu_sales,global_sales
0,1,Halo 3,Shooter,2007.0,7.22,3.93,12.32
1,2,FIFA 14,Sports,2013.0,2.04,8.74,12.20
2,3,GTA V,Action,2013.0,7.01,9.27,20.32
3,4,Minecraft,Misc,2013.0,7.26,4.18,13.00
4,5,Mario Kart Wii,Racing,2008.0,15.85,12.88,35.82
5,6,Tetris,Puzzle,1989.0,NaN,NaN,NaN
6,7,God of War,Action,2005.0,2.56,2.12,5.17
7,8,The Sims 3,Simulation,2009.0,4.13,4.73,10.20
8,9,NaN,NaN,NaN,1.50,0.80,2.80

---
## Section 3 — Chaining merges

### Exercise 3.1
Chain two merges:
1. Left join `games` with `sales` on `game_id`
2. Left join the result with `scores` on `game_id`

Save to `full`. How many columns does `full` have?

In [ ]:
# Your code here
join_gam_sal = pd.merge(games,sales,how='left',on='game_id')
full = pd.merge(join_gam_sal, scores, how='left', on='game_id')
display(full)

#Full has 9 columns

,game_id,title,genre,year,na_sales,eu_sales,global_sales,critic_score,user_score
0,1,Halo 3,Shooter,2007,7.22,3.93,12.32,94.0,8.3
1,2,FIFA 14,Sports,2013,2.04,8.74,12.20,NaN,NaN
2,3,GTA V,Action,2013,7.01,9.27,20.32,97.0,8.2
3,4,Minecraft,Misc,2013,7.26,4.18,13.00,82.0,7.9
4,5,Mario Kart Wii,Racing,2008,15.85,12.88,35.82,82.0,8.9
5,6,Tetris,Puzzle,1989,NaN,NaN,NaN,NaN,NaN
6,7,God of War,Action,2005,2.56,2.12,5.17,94.0,8.7
7,8,The Sims 3,Simulation,2009,4.13,4.73,10.20,NaN,NaN

### Exercise 3.2
From `full`, show only the rows where **both** `critic_score` and `global_sales` are available.
Sort by `global_sales` descending.

In [ ]:
# Your code here
full[full['critic_score'].notnull() & full['global_sales'].notnull()].sort_values('global_sales', ascending = False)

,game_id,title,genre,year,na_sales,eu_sales,global_sales,critic_score,user_score
4,5,Mario Kart Wii,Racing,2008,15.85,12.88,35.82,82.0,8.9
2,3,GTA V,Action,2013,7.01,9.27,20.32,97.0,8.2
3,4,Minecraft,Misc,2013,7.26,4.18,13.00,82.0,7.9
0,1,Halo 3,Shooter,2007,7.22,3.93,12.32,94.0,8.3
6,7,God of War,Action,2005,2.56,2.12,5.17,94.0,8.7

In [23]:
full.dropna(subset=['critic_score','global_sales'])\
    .sort_values('global_sales', ascending=False)

,game_id,title,genre,year,na_sales,eu_sales,global_sales,critic_score,user_score
4,5,Mario Kart Wii,Racing,2008,15.85,12.88,35.82,82.0,8.9
2,3,GTA V,Action,2013,7.01,9.27,20.32,97.0,8.2
3,4,Minecraft,Misc,2013,7.26,4.18,13.00,82.0,7.9
0,1,Halo 3,Shooter,2007,7.22,3.93,12.32,94.0,8.3
6,7,God of War,Action,2005,2.56,2.12,5.17,94.0,8.7

---
## Section 4 — Merge with index and different key names

### Exercise 4.1 — Merge on index
Set `game_id` as the index for both `games` and `sales`.
Then merge them using `left_index=True` and `right_index=True`.

In [ ]:
games.set_index("game_id")
sales = sales.set_index("game_id")

In [34]:
# Your code here
display(games)
display(sales)
pd.merge(games, sales, how='inner', left_index=True, right_index=True)

                  title       genre  year
game_id
1                Halo 3     Shooter  2007
2               FIFA 14      Sports  2013
3                 GTA V      Action  2013
4             Minecraft        Misc  2013
5        Mario Kart Wii      Racing  2008
6                Tetris      Puzzle  1989
7            God of War      Action  2005
8            The Sims 3  Simulation  2009

         na_sales  eu_sales  global_sales
game_id
1            7.22      3.93         12.32
2            2.04      8.74         12.20
3            7.01      9.27         20.32
4            7.26      4.18         13.00
5           15.85     12.88         35.82
7            2.56      2.12          5.17
8            4.13      4.73         10.20
9            1.50      0.80          2.80

                  title       genre  year  na_sales  eu_sales  global_sales
game_id
1                Halo 3     Shooter  2007      7.22      3.93         12.32
2               FIFA 14      Sports  2013      2.04      8.74         12.20
3                 GTA V      Action  2013      7.01      9.27         20.32
4             Minecraft        Misc  2013      7.26      4.18         13.00
5        Mario Kart Wii      Racing  2008     15.85     12.88         35.82
7            God of War      Action  2005      2.56      2.12          5.17
8            The Sims 3  Simulation  2009      4.13      4.73         10.20

### Exercise 4.2 — Different key column names
Rename `game_id` to `id` in `sales`. Now merge `games` and the renamed `sales`
using `left_on='game_id'` and `right_on='id'`.
Drop the redundant `id` column afterward.

In [39]:
# Your code here
sales.index.name = 'id'
display(sales)

    na_sales  eu_sales  global_sales
id
1       7.22      3.93         12.32
2       2.04      8.74         12.20
3       7.01      9.27         20.32
4       7.26      4.18         13.00
5      15.85     12.88         35.82
7       2.56      2.12          5.17
8       4.13      4.73         10.20
9       1.50      0.80          2.80

In [40]:
pd.merge(games, sales, how='inner', left_on='game_id', right_on='id')

            title       genre  year  na_sales  eu_sales  global_sales
0          Halo 3     Shooter  2007      7.22      3.93         12.32
1         FIFA 14      Sports  2013      2.04      8.74         12.20
2           GTA V      Action  2013      7.01      9.27         20.32
3       Minecraft        Misc  2013      7.26      4.18         13.00
4  Mario Kart Wii      Racing  2008     15.85     12.88         35.82
5      God of War      Action  2005      2.56      2.12          5.17
6      The Sims 3  Simulation  2009      4.13      4.73         10.20

### Exercise 4.3 — Handling duplicate column names
Both `games` and a version of `sales` have a column called `year` added.
Merge them and use `suffixes=('_game', '_sale')` to distinguish the columns.

In [ ]:
sales_with_year = sales.copy()
sales_with_year['year'] = [2007, 2013, 2014, 2013, 2008, 2005, 2010, 2020]
# Your code here

---
## 🔥 Final Challenge

Build the most complete dataset possible from all four tables.

**Step 1:** Concat `publishers_a` and `publishers_b` into `publishers`. Reset index.

**Step 2:** Inner join `games` with `sales` on `game_id`. Save as `gs`.

**Step 3:** Left join `gs` with `scores` on `game_id`. Save as `gss`.

**Step 4:** Left join `gss` with `publishers` on `title`. Save as `full`.

**Step 5:** Print the shape of `full`. How many games are missing a publisher?

**Step 6:** Fill missing `publisher` values with `'Unknown'`.

**Step 7:** Show the top 5 games by `global_sales` with columns: `title`, `publisher`, `genre`, `global_sales`, `critic_score`.

In [ ]:
# Step 1
publishers = pd.concat([publishers_a, publishers_b]).reset_index(drop=True)
display(publishers)

In [ ]:
# Step 2
gs = pd.merge(games,sales, how = 'inner', on='game_id')
display(gs)

In [47]:
# Step 3
gss = pd.merge(gs,scores,how = 'left', on='game_id')

In [ ]:
# Step 4
full = pd.merge(gss, publishers, how='left', on='title')
display(full)

In [ ]:
# Step 5
print("Shape:", full.shape)
print("Missing publisher:", full['publisher'].isnull().sum())

In [ ]:
# Step 6
full['publisher'] = full['publisher'].fillna('Unknown')
display(full)

In [56]:
# Step 7
full[['title','publisher','genre','global_sales','critic_score']].nlargest(5,'global_sales')

            title  publisher    genre  global_sales  critic_score
4  Mario Kart Wii   Nintendo   Racing         35.82          82.0
2           GTA V   Take-Two   Action         20.32          97.0
3       Minecraft  Microsoft     Misc         13.00          82.0
0          Halo 3  Microsoft  Shooter         12.32          94.0
1         FIFA 14  EA Sports   Sports         12.20           NaN