# 🎮 Pandas Practice — 03: Useful Methods

**Dataset:** Video game global sales (mini VGChartz).
This notebook covers the most commonly used pandas methods beyond basic selection.
Work through each section in order — the Challenge at the end ties everything together.

---
## Setup — run this cell first!

In [1]:
import numpy as np
import pandas as pd
import io
raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
Resident Evil 4,Action,PS2,2005,Capcom,2.0,1.91,1.06,5.97,96,8.9
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92,9.0
"""

df = pd.read_csv(io.StringIO(raw))
print("Dataset loaded! Shape:", df.shape)
df.head()

Dataset loaded! Shape: (26, 11)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN

---
## Section 1 — `.apply()` with a named function

### Exercise 1.1
Write a function called `sales_tier` that takes a `Global_Sales` value and returns:
- `'Blockbuster'` if sales >= 30M
- `'Hit'` if sales >= 10M
- `'Mid'` if sales >= 5M
- `'Niche'` otherwise

Apply it to the `Global_Sales` column and store the result in a new column called `'Tier'`.
Display the first 10 rows showing `Title`, `Global_Sales`, and `Tier`.

In [2]:
# Your code here
def sales_tier(global_sales):
    if global_sales >= 30:
        return 'Blockbuster'
    elif global_sales >=10:
        return 'Hit'
    elif global_sales >= 5:
        return 'Mid'
    else:
        return 'Niche'
df['Tier'] = df['Global_Sales'].apply(sales_tier)
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster

### Exercise 1.2
Write a function called `abbreviate` that takes a publisher name and returns only the **first 3 characters** (uppercased).
Apply it to the `Publisher` column and store in a new column `'Pub_Code'`.

In [5]:
# Your code here
def abbreviate(publisher):
    return str(publisher)[:3].upper()

df['Pub_Code'] = df['Publisher'].apply(abbreviate)
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN

---
## Section 2 — `.apply()` with lambda

### Exercise 2.1
Using a **lambda**, create a new column `'NA_Pct'` that represents North America sales
as a percentage of Global Sales, rounded to 1 decimal.
*(e.g. 41.49 / 82.74 * 100 → 50.1)*

In [7]:
# Your code here
def percentage(america,global_sales):
    return round(america/global_sales*100,1)

df['NA_Pct'] = np.vectorize(percentage)(df['NA_Sales'], df['Global_Sales'])
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9

### Exercise 2.2
Using a **lambda**, create a column `'Old_Game'` that is `True` if the game was released
before the year 2000, and `False` otherwise.

In [11]:
# Your code here
def truish(year):
    return year < 2000

df['Old_Game']= df['Year'].apply(lambda num: num < 2000)
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True

### Exercise 2.3
Using a **lambda**, create a column `'Score_Label'` from `Critic_Score`:
- `'Great'` if score >= 90
- `'Good'` if score >= 75
- `'Average'` otherwise

*Note: some rows have NaN in Critic_Score — your lambda should handle that.
Hint: check `pd.isna(x)` inside the lambda.*

In [12]:
# Your code here
df['Score_Label'] = df['Critic_Score'].apply(lambda x: 'N/A' if pd.isna(x) else ('Great' if x <= 90 else('Good' if x >= 75 else 'Average')))
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A

---
## Section 3 — `.apply()` across multiple columns

### Exercise 3.1
Write a function called `market_focus` that takes `na_sales` and `eu_sales` and returns:
- `'NA Dominant'` if NA_Sales > EU_Sales * 1.5
- `'EU Dominant'` if EU_Sales > NA_Sales * 1.5
- `'Balanced'` otherwise

Apply it using a lambda across `['NA_Sales', 'EU_Sales']` with `axis=1`.
Store in a new column `'Market_Focus'`.

In [15]:
# Your code here
def market_focus(na_sales, eu_sales):
    if na_sales > eu_sales*1.5:
        return 'NA Dominant'
    elif eu_sales > na_sales*1.5:
        return 'EU Dominant'
    else:
        return 'Balanced'


df['Market_Focus'] = df[['NA_Sales', 'EU_Sales']].apply(
    lambda row: market_focus(row['NA_Sales'], row['EU_Sales']), axis=1
)
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced

### Exercise 3.2 — `np.vectorize` (faster alternative)
Rewrite the same `market_focus` logic but this time apply it using `np.vectorize`
instead of `.apply()`. Store the result in `'Market_Focus_v2'`.

Then confirm both columns are identical using `==` and `.all()`.

In [17]:
# Your code here
df['Market_Focus_V2'] = np.vectorize(market_focus)(df['NA_Sales'], df['EU_Sales'])

df['Comparison'] = (df['Market_Focus_V2'] == df['Market_Focus']).all
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...

---
## Section 4 — `sort_values()`

### Exercise 4.1
Sort the DataFrame by `Global_Sales` in **descending** order. Show the top 5.

In [18]:
# Your code here
df.sort_values('Global_Sales', ascending=False)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN,Blockbuster,NIN,76.7,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5,Blockbuster,NIN,37.9,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6,Hit,NIN,48.3,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4,Hit,NIN,51.0,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN,Hit,NIN,95.1,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5,Hit,ACT,71.7,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2,Hit,TAK,34.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2,Hit,SON,45.7,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9,Hit,MIC,55.8,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3,Hit,MIC,58.6,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.0,6.7,Hit,EA,16.7,False,Great,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN,Hit,CAP,52.9,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
24,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8,Hit,EA,40.5,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
25,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.0,9.0,Mid,SQU,31.0,True,Good,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN,Mid,ATA,84.2,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN,Mid,NIN,50.8,True,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN,Mid,NIN,83.5,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.0,8.9,Mid,CAP,33.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7,Mid,SON,49.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...

### Exercise 4.2
Sort by `Genre` (ascending) first, then by `Global_Sales` (descending) within each genre.
Show the first 10 rows.

In [19]:
# Your code here
df.sort_values(['Genre', 'Global_Sales'],ascending=[True,False])

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2,Hit,TAK,34.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN,Mid,NIN,83.5,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.0,8.9,Mid,CAP,33.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7,Mid,SON,49.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN,Hit,CAP,52.9,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6,Hit,NIN,48.3,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9,Hit,MIC,55.8,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5,Blockbuster,NIN,37.9,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4,Hit,NIN,51.0,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN,Mid,NIN,50.8,True,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN,Blockbuster,NIN,76.7,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN,Mid,ATA,84.2,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2,Hit,SON,45.7,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
25,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.0,9.0,Mid,SQU,31.0,True,Good,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN,Hit,NIN,95.1,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5,Hit,ACT,71.7,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3,Hit,MIC,58.6,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
24,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8,Hit,EA,40.5,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.0,6.7,Hit,EA,16.7,False,Great,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...

---
## Section 5 — Statistical methods

### Exercise 5.1 — `describe()`
Get the statistical summary of the DataFrame and transpose it so it's easier to read.
Which column has the highest standard deviation?

In [22]:
# Your code here
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Year,26.0,2001.307692,9.653059,1982.00,1994.5000,2005.000,2008.7500,2013.00
NA_Sales,26.0,11.628077,9.476648,2.00,6.3525,8.150,14.6875,41.49
EU_Sales,26.0,5.976538,5.853270,0.00,2.3225,4.455,8.8525,29.02
JP_Sales,26.0,2.302308,2.615895,0.04,0.2125,1.065,3.6475,10.22
Global_Sales,26.0,21.295769,16.382533,5.17,10.4400,13.990,29.7625,82.74
Critic_Score,19.0,87.105263,9.338658,58.00,83.5000,87.000,94.5000,97.00
User_Score,18.0,8.100000,0.750686,6.60,7.9250,8.200,8.6500,9.00
NA_Pct,26.0,54.626923,19.399847,16.70,41.4250,50.450,72.1500,95.10

### Exercise 5.2 — `corr()`
Calculate the correlation matrix for `NA_Sales`, `EU_Sales`, `JP_Sales`, and `Global_Sales`.
Which two variables are most correlated with each other (excluding Global_Sales vs itself)?

In [25]:
# Your code here
df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales']].corr()

              NA_Sales  EU_Sales  JP_Sales  Global_Sales
NA_Sales      1.000000  0.545393  0.396855      0.905252
EU_Sales      0.545393  1.000000  0.354119      0.829805
JP_Sales      0.396855  0.354119  1.000000      0.541947
Global_Sales  0.905252  0.829805  0.541947      1.000000

### Exercise 5.3 — `idxmax()` / `idxmin()`
1. Find the **index** of the row with the highest `Critic_Score`.
2. Use that index with `.iloc[]` to display the full row.
3. Do the same for the **lowest** `Global_Sales`.

In [29]:
# Your code here
df['Critic_Score'].idxmax()
df.iloc[df['Critic_Score'].idxmax()]

df.iloc[df['Global_Sales'].idxmin()]

Title                                                     God of War
Genre                                                         Action
Platform                                                         PS2
Year                                                            2005
Publisher                                                       Sony
NA_Sales                                                        2.56
EU_Sales                                                        2.12
JP_Sales                                                        0.07
Global_Sales                                                    5.17
Critic_Score                                                    94.0
User_Score                                                       8.7
Tier                                                             Mid
Pub_Code                                                         SON
NA_Pct                                                          49.5
Old_Game                                                       False
Score_Label                                                     Good
Market_Focus                                                Balanced
Market_Focus_V2                                             Balanced
Comparison         <bound method Series.all of 0     True\n1     ...
Name: 21, dtype: object

---
## Section 6 — Counting and uniqueness

### Exercise 6.1 — `value_counts()`
How many games are in each `Genre`? Show the counts sorted from most to least.

In [32]:
# Your code here
df['Genre'].value_counts().sort_values(ascending=False)

Genre
Shooter         5
Platform        4
Action          4
Sports          3
Racing          2
Role-Playing    2
Puzzle          2
Misc            2
Simulation      1
Fighting        1
Name: count, dtype: int64

### Exercise 6.2 — `unique()` and `nunique()`
1. Print all unique platforms in the dataset using `.unique()`.
2. How many unique publishers are there? Use `.nunique()`.

In [34]:
# Your code here
df['Platform'].unique()
df['Platform'].nunique()

12

---
## Section 7 — `replace()` and `map()`

### Exercise 7.1 — `replace()`
In the `'Tier'` column you created in Exercise 1.1, replace `'Niche'` with `'Long Tail'`.
Save the change back to the DataFrame.

In [35]:
# Your code here
df['Tier'] = df['Tier'].replace('Niche', 'Long Tail')
df

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN,Blockbuster,NIN,76.7,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5,Blockbuster,NIN,37.9,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6,Hit,NIN,48.3,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4,Hit,NIN,51.0,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN,Hit,NIN,95.1,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5,Hit,ACT,71.7,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.0,6.7,Hit,EA,16.7,False,Great,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2,Hit,TAK,34.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN,Mid,NIN,83.5,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2,Hit,SON,45.7,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3,Hit,MIC,58.6,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9,Hit,MIC,55.8,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8,Hit,EA,40.5,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN,Hit,CAP,52.9,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN,Mid,ATA,84.2,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN,Mid,NIN,50.8,True,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7,Mid,SON,49.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.0,8.9,Mid,CAP,33.5,False,Good,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
24,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.0,8.2,Hit,MIC,76.1,False,Good,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...
25,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.0,9.0,Mid,SQU,31.0,True,Good,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...

### Exercise 7.2 — `map()`
Create a dictionary that maps each genre to a category:
```python
genre_map = {
    'Action': 'Core', 'Shooter': 'Core', 'Fighting': 'Core', 'Role-Playing': 'Core',
    'Sports': 'Casual', 'Racing': 'Casual', 'Misc': 'Casual', 'Simulation': 'Casual',
    'Platform': 'Family', 'Puzzle': 'Family'
}
```
Use `.map()` to create a new column `'Category'` from the `Genre` column.

In [36]:
genre_map = {
    'Action': 'Core', 'Shooter': 'Core', 'Fighting': 'Core', 'Role-Playing': 'Core',
    'Sports': 'Casual', 'Racing': 'Casual', 'Misc': 'Casual', 'Simulation': 'Casual',
    'Platform': 'Family', 'Puzzle': 'Family'
}
# Your code here
df['Category'] = df['Genre'].map(genre_map)
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison,Category
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,Blockbuster,NIN,72.3,True,N/A,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...,Family
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,Blockbuster,NIN,44.2,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Core

---
## Section 8 — Duplicates

### Exercise 8.1
1. Use `.duplicated()` to check how many duplicate rows exist in the dataset.
2. Use `.drop_duplicates()` to remove them and save back to `df`.
3. Confirm the new shape of the DataFrame.

In [40]:
# Your code here
df.duplicated()
df = df.drop_duplicates()
df.shape

(25, 20)

---
## Section 9 — `between()`, `sample()`, `nlargest()`

### Exercise 9.1 — `between()`
Filter games where `Global_Sales` is between 10M and 25M (inclusive).
How many games fall in that range?

In [45]:
# Your code here
len(df[df['Global_Sales'].between(10,25, inclusive = 'both')])

9

### Exercise 9.2 — `sample()`
1. Take a random sample of 5 games (use `random_state=42` for reproducibility).
2. Take a sample of 20% of the dataset using `frac=`.

In [48]:
# Your code here
df.sample(5, random_state = 42)
df.sample(frac = 0.2)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison,Category
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
25,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.0,9.0,Mid,SQU,31.0,True,Good,EU Dominant,EU Dominant,<bound method Series.all of 0 True\n1 ...,Core
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,Blockbuster,NIN,35.9,True,N/A,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Core
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5,Hit,ACT,71.7,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...,Core

### Exercise 9.3 — `nlargest()` / `nsmallest()`
1. Get the top 5 games by `EU_Sales`.
2. Get the 3 games with the lowest `Critic_Score` (ignore NaN rows — filter them out first).

In [50]:
# Your code here
df.nlargest(5, 'EU_Sales')
df[df['Critic_Score'].notna()].nsmallest(3,'Critic_Score')

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Tier,Pub_Code,NA_Pct,Old_Game,Score_Label,Market_Focus,Market_Focus_V2,Comparison,Category
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6,Hit,NIN,48.3,False,Great,NA Dominant,NA Dominant,<bound method Series.all of 0 True\n1 ...,Casual
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,Blockbuster,NIN,50.1,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,Blockbuster,NIN,47.7,False,Great,Balanced,Balanced,<bound method Series.all of 0 True\n1 ...,Casual

---
## 🔥 Final Challenge

You're preparing a **publisher performance report**. Starting from a clean `df` (after dropping duplicates), complete all steps in order:

**Step 1:** Drop duplicate rows (if you haven't already).

**Step 2:** Create a `'Tier'` column using the `sales_tier` function from Exercise 1.1.

**Step 3:** Create a `'Market_Focus'` column using `market_focus` from Exercise 3.1 (use `np.vectorize`).

**Step 4:** Using `value_counts()`, show how many games fall into each `Tier`.

**Step 5:** Sort the full DataFrame by `Global_Sales` descending and show the top 10 with columns:
`Title`, `Publisher`, `Global_Sales`, `Tier`, `Market_Focus`, `Critic_Score`.

**Step 6:** Among the top 10, what is the **correlation** between `Global_Sales` and `Critic_Score`?
*(Hint: filter to top 10 first, then use `.corr()` on just those two columns)*

**Step 7:** Replace `'Long Tail'` back to `'Niche'` in the `Tier` column (undo Exercise 7.1),
then use `.map()` with `genre_map` to add a `'Category'` column.
Show `value_counts()` for `Category` among games in the `'Blockbuster'` tier on
ly.

In [ ]:
# Step 1
df.drop_duplicates()

In [53]:
# Step 2
df['Tier'] = df['Global_Sales'].apply(sales_tier)

In [52]:
# Step 3
df['Market_Focus'] = df[['NA_Sales', 'EU_Sales']].apply(
    lambda row: market_focus(row['NA_Sales'], row['EU_Sales']), axis=1
)

In [ ]:
# Step 4
df['Tier'].value_counts()

In [ ]:
# Step 5
top10 = df.nlargest(10,'Global_Sales')[['Title', 'Publisher', 'Global_Sales', 'Tier', 'Market_Focus', 'Critic_Score']]

In [61]:
# Step 6
top10[['Global_Sales', 'Critic_Score']].corr()

              Global_Sales  Critic_Score
Global_Sales      1.000000     -0.091663
Critic_Score     -0.091663      1.000000

In [ ]:
# Step 7

---
# 📋 SOLUTIONS

*(Scroll down only after attempting the exercises!)*

.

.

.

.

.

.

.

.

.

.

In [ ]:
# ── SETUP (re-run to get a clean df) ──
import numpy as np
import pandas as pd
import io

raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
Resident Evil 4,Action,PS2,2005,Capcom,2.0,1.91,1.06,5.97,96,8.9
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92,9.0
"""
df = pd.read_csv(io.StringIO(raw))

In [ ]:
# ── 1.1 ──
def sales_tier(sales):
    if sales >= 30:
        return 'Blockbuster'
    elif sales >= 10:
        return 'Hit'
    elif sales >= 5:
        return 'Mid'
    else:
        return 'Niche'

df['Tier'] = df['Global_Sales'].apply(sales_tier)
df[['Title', 'Global_Sales', 'Tier']].head(10)

In [ ]:
# ── 1.2 ──
def abbreviate(name):
    return str(name)[:3].upper()

df['Pub_Code'] = df['Publisher'].apply(abbreviate)
df[['Publisher', 'Pub_Code']].head()

In [ ]:
# ── 2.1 ──
df['NA_Pct'] = df['NA_Sales'].apply(lambda x: round(x / df['Global_Sales'][df['NA_Sales'] == x].values[0] * 100, 1))
# Cleaner version using vectorized division:
df['NA_Pct'] = (df['NA_Sales'] / df['Global_Sales'] * 100).round(1)
df[['Title', 'NA_Sales', 'Global_Sales', 'NA_Pct']].head()

In [ ]:
# ── 2.2 ──
df['Old_Game'] = df['Year'].apply(lambda y: y < 2000)
df[['Title', 'Year', 'Old_Game']].head(10)

In [ ]:
# ── 2.3 ──
df['Score_Label'] = df['Critic_Score'].apply(
    lambda x: 'N/A' if pd.isna(x) else ('Great' if x >= 90 else ('Good' if x >= 75 else 'Average'))
)
df[['Title', 'Critic_Score', 'Score_Label']].head(10)

In [ ]:
# ── 3.1 ──
def market_focus(na, eu):
    if na > eu * 1.5:
        return 'NA Dominant'
    elif eu > na * 1.5:
        return 'EU Dominant'
    else:
        return 'Balanced'

df['Market_Focus'] = df[['NA_Sales', 'EU_Sales']].apply(
    lambda row: market_focus(row['NA_Sales'], row['EU_Sales']), axis=1
)
df[['Title', 'NA_Sales', 'EU_Sales', 'Market_Focus']].head(10)

In [ ]:
# ── 3.2 ──
df['Market_Focus_v2'] = np.vectorize(market_focus)(df['NA_Sales'], df['EU_Sales'])

# Confirm both columns match
print("All equal:", (df['Market_Focus'] == df['Market_Focus_v2']).all())

In [ ]:
# ── 4.1 ──
df.sort_values('Global_Sales', ascending=False).head(5)[['Title', 'Global_Sales']]

In [ ]:
# ── 4.2 ──
df.sort_values(['Genre', 'Global_Sales'], ascending=[True, False]).head(10)[['Title', 'Genre', 'Global_Sales']]

In [ ]:
# ── 5.1 ──
summary = df.describe().transpose()
print(summary)
print("\nHighest std:", summary['std'].idxmax())

In [ ]:
# ── 5.2 ──
corr = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales']].corr()
print(corr)
# NA_Sales and Global_Sales are the most correlated (expected — NA drives global sales)

In [ ]:
# ── 5.3 ──
idx_max = df['Critic_Score'].idxmax()
print("Best critic score row:")
print(df.iloc[idx_max])

idx_min = df['Global_Sales'].idxmin()
print("\nLowest global sales row:")
print(df.iloc[idx_min])

In [ ]:
# ── 6.1 ──
df['Genre'].value_counts()

In [ ]:
# ── 6.2 ──
print("Unique platforms:", df['Platform'].unique())
print("\nNumber of unique publishers:", df['Publisher'].nunique())

In [ ]:
# ── 7.1 ──
df['Tier'] = df['Tier'].replace(to_replace='Niche', value='Long Tail')
df['Tier'].value_counts()

In [ ]:
# ── 7.2 ──
genre_map = {
    'Action': 'Core', 'Shooter': 'Core', 'Fighting': 'Core', 'Role-Playing': 'Core',
    'Sports': 'Casual', 'Racing': 'Casual', 'Misc': 'Casual', 'Simulation': 'Casual',
    'Platform': 'Family', 'Puzzle': 'Family'
}
df['Category'] = df['Genre'].map(genre_map)
df[['Genre', 'Category']].drop_duplicates()

In [ ]:
# ── 8.1 ──
print("Duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape after dropping duplicates:", df.shape)

In [ ]:
# ── 9.1 ──
between_filter = df[df['Global_Sales'].between(10, 25)]
print(f"Games between 10M-25M: {len(between_filter)}")
between_filter[['Title', 'Global_Sales']]

In [ ]:
# ── 9.2 ──
print(df.sample(5, random_state=42)[['Title', 'Global_Sales']])
print(f"\n20% sample size: {len(df.sample(frac=0.2, random_state=42))}")

In [ ]:
# ── 9.3 ──
print("Top 5 by EU Sales:")
print(df.nlargest(5, 'EU_Sales')[['Title', 'EU_Sales']])

print("\n3 lowest Critic Scores (excluding NaN):")
print(df.dropna(subset=['Critic_Score']).nsmallest(3, 'Critic_Score')[['Title', 'Critic_Score']])

In [ ]:
# ── FINAL CHALLENGE ──

# Step 1
df = df.drop_duplicates()

# Step 2
def sales_tier(sales):
    if sales >= 30: return 'Blockbuster'
    elif sales >= 10: return 'Hit'
    elif sales >= 5: return 'Mid'
    else: return 'Niche'

df['Tier'] = df['Global_Sales'].apply(sales_tier)

# Step 3
def market_focus(na, eu):
    if na > eu * 1.5: return 'NA Dominant'
    elif eu > na * 1.5: return 'EU Dominant'
    else: return 'Balanced'

df['Market_Focus'] = np.vectorize(market_focus)(df['NA_Sales'], df['EU_Sales'])

# Step 4
print("Games per Tier:")
print(df['Tier'].value_counts())

# Step 5
top10 = df.sort_values('Global_Sales', ascending=False).head(10)
print("\nTop 10 games:")
print(top10[['Title', 'Publisher', 'Global_Sales', 'Tier', 'Market_Focus', 'Critic_Score']])

# Step 6
corr = top10[['Global_Sales', 'Critic_Score']].corr()
print("\nCorrelation (Global Sales vs Critic Score in top 10):")
print(corr)

# Step 7
df['Tier'] = df['Tier'].replace('Long Tail', 'Niche')
genre_map = {
    'Action': 'Core', 'Shooter': 'Core', 'Fighting': 'Core', 'Role-Playing': 'Core',
    'Sports': 'Casual', 'Racing': 'Casual', 'Misc': 'Casual', 'Simulation': 'Casual',
    'Platform': 'Family', 'Puzzle': 'Family'
}
df['Category'] = df['Genre'].map(genre_map)
blockbusters = df[df['Tier'] == 'Blockbuster']
print("\nCategory breakdown among Blockbusters:")
print(blockbusters['Category'].value_counts())