# 🎮 Pandas Practice — 01: DataFrames
**Dataset:** Video game global sales data (a mini version of the famous VGChartz dataset).

---
## Setup — run this cell first!

In [45]:
import numpy as np
import pandas as pd
import io

raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
"""
df = pd.read_csv(io.StringIO(raw))
print("Dataset loaded! Shape:", df.shape)

Dataset loaded! Shape: (22, 11)

## Section 1 — Exploring the DataFrame

### Exercise 1.1
Display the first 5 rows and the last 3 rows of the dataset.

In [5]:
# Your code here
df.head()
df.tail()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7

### Exercise 1.2
Print:
- The column names
- The index
- The shape (rows, columns)
- A full summary with `.info()`

In [9]:
# Your code here
print(f"Column names {df.columns}")
print(f"Index names {df.index}")
print(f"Shape {df.shape}")
print(f"Info {df.info()}")

Column names Index(['Title', 'Genre', 'Platform', 'Year', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Global_Sales', 'Critic_Score', 'User_Score'],
      dtype='object')
Index names RangeIndex(start=0, stop=22, step=1)
Shape (22, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         22 non-null     object
 1   Genre         22 non-null     object
 2   Platform      22 non-null     object
 3   Year          22 non-null     int64
 4   Publisher     22 non-null     object
 5   NA_Sales      22 non-null     float64
 6   EU_Sales      22 non-null     float64
 7   JP_Sales      22 non-null     float64
 8   Global_Sales  22 non-null     float64
 9   Critic_Score  15 non-null     float64
 10  User_Score    14 non-null     float64
dtypes: float64(6), int64(1), object(4)
memory usage: 2.0+ KB
Info None

### Exercise 1.3
Get descriptive statistics for all numeric columns using `.describe()`. Then transpose it so it's easier to read.

In [11]:
# Your code here
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Year,22.0,2001.090909,10.423915,1982.00,1992.500,2006.00,2009.0000,2013.00
NA_Sales,22.0,12.742727,9.834757,2.04,6.595,9.54,15.4925,41.49
EU_Sales,22.0,6.472727,6.212604,0.00,2.415,4.89,9.1225,29.02
JP_Sales,22.0,2.519091,2.737689,0.04,0.285,1.47,3.7850,10.22
Global_Sales,22.0,23.440000,16.951176,5.17,11.990,20.42,30.1975,82.74
Critic_Score,15.0,85.133333,9.575763,58.00,82.000,86.00,91.5000,97.00
User_Score,14.0,7.964286,0.777181,6.60,7.600,8.20,8.4750,8.90

## Section 2 — Selecting columns

### Exercise 2.1 — Single column
Select only the `'Title'` column.

In [12]:
# Your code here
df['Title']

0                   Wii Sports
1             Super Mario Bros
2               Mario Kart Wii
3            Wii Sports Resort
4             Pokemon Red/Blue
5                       Tetris
6         New Super Mario Bros
7                     Wii Play
8     New Super Mario Bros Wii
9                    Duck Hunt
10      Call of Duty Black Ops
11                     FIFA 14
12          Grand Theft Auto V
13         The Legend of Zelda
14              Gran Turismo 3
15                      Halo 3
16                   Minecraft
17                  The Sims 3
18           Street Fighter II
19                     Pac-Man
20         Donkey Kong Country
21                  God of War
Name: Title, dtype: object

### Exercise 2.2 — Multiple columns
Select `'Title'`, `'Genre'`, and `'Global_Sales'` at the same time.

In [15]:
# Your code here
df[['Title','Genre','Global_Sales']]

                       Title         Genre  Global_Sales
0                 Wii Sports        Sports         82.74
1           Super Mario Bros      Platform         40.24
2             Mario Kart Wii        Racing         35.82
3          Wii Sports Resort        Sports         33.00
4           Pokemon Red/Blue  Role-Playing         31.37
5                     Tetris        Puzzle         30.26
6       New Super Mario Bros      Platform         30.01
7                   Wii Play          Misc         29.02
8   New Super Mario Bros Wii      Platform         28.62
9                  Duck Hunt       Shooter         28.31
10    Call of Duty Black Ops       Shooter         20.52
11                   FIFA 14        Sports         12.20
12        Grand Theft Auto V        Action         20.32
13       The Legend of Zelda        Action          7.80
14            Gran Turismo 3        Racing         14.98
15                    Halo 3       Shooter         12.32
16                 Minecraft          Misc         13.00
17                The Sims 3    Simulation         10.20
18         Street Fighter II      Fighting         11.92
19                   Pac-Man        Puzzle          9.28
20       Donkey Kong Country      Platform          8.58
21                God of War        Action          5.17

### Exercise 2.3 — Create new columns
Create two new columns:
1. `'Sales_Ratio_NA'` = NA_Sales divided by Global_Sales (proportion of global sales from North America). Round to 3 decimals.
2. `'Is_Nintendo'` = True if Publisher is `'Nintendo'`, False otherwise.

Display the first 5 rows after adding them.

In [22]:
# Your code here
df['Sales_Ratio_NA'] = np.round(df['NA_Sales'] / df['Global_Sales'] ,3)
df['Is_Nintendo'] = (df['Publisher'] == 'Nintendo')
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Sales_Ratio_NA,Is_Nintendo
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,0.501,True
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,0.723,True
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,0.442,True
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,0.477,True
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,0.359,True

### Exercise 2.4 — Drop a column
Drop the `'Sales_Ratio_NA'` column you just created (don't forget `axis=1`). Confirm it's gone with `.head()`.

In [27]:
# Your code here
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Is_Nintendo
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,True
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,True
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,True
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,True
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,True

## Section 3 — Index and row selection

### Exercise 3.1 — Set the index
Set `'Title'` as the DataFrame index. Save it back to `df`.

In [31]:
# Your code here
df.head()

,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Is_Nintendo
Title,,,,,,,,,,,
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0,True
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN,True
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9,True
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8,True
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN,True

### Exercise 3.2 — Select rows with `.loc` and `.iloc`
1. Use `.iloc` to get the **third** row (integer position 2).
2. Use `.loc` to get the row for `'Minecraft'`.

In [33]:
# Your code here
df.iloc[2]
df.loc['Minecraft']

Genre                Misc
Platform             X360
Year                 2013
Publisher       Microsoft
NA_Sales             7.26
EU_Sales             4.18
JP_Sales             0.19
Global_Sales         13.0
Critic_Score         82.0
User_Score            7.9
Is_Nintendo         False
Name: Minecraft, dtype: object

### Exercise 3.3 — Multiple rows
Use `.loc` to get the rows for `'Halo 3'` and `'God of War'` at the same time.

In [34]:
# Your code here
df.loc[['Halo 3', 'God of War']]

,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score,Is_Nintendo
Title,,,,,,,,,,,
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3,False
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7,False

### Exercise 3.4 — Reset the index
Reset the index back to the default integer index and save it to `df`.

In [46]:
# Your code here
df.head()

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN

## 🔥 Challenge — Exercise 3.5
Starting from the clean `df` (default integer index):

1. Set `'Title'` as the index.
2. Create a new column `'EU_plus_JP'` = EU_Sales + JP_Sales.
3. Using `.loc`, retrieve only the columns `'Genre'`, `'Global_Sales'`, and `'EU_plus_JP'` for the games `'Grand Theft Auto V'` and `'The Legend of Zelda'`.
4. Print how many rows have `Global_Sales` above 20 million. *(Hint: use `len()` or `.shape`)*

In [ ]:
# Your code here
df = df.set_index('Title')
df.head()

In [49]:
df['EU_plus_JP'] = df['EU_Sales'] + df['JP_Sales']

In [52]:
df.loc[['Grand Theft Auto V', 'The Legend of Zelda'], ['Genre', 'Global_Sales', 'EU_plus_JP']]

                      Genre  Global_Sales  EU_plus_JP
Title
Grand Theft Auto V   Action         20.32       10.24
The Legend of Zelda  Action          7.80        1.07

In [55]:
len(df[df['Global_Sales'] > 20])

12

---
# 📋 SOLUTIONS
*(Scroll down only after attempting the exercises!)*

.

.

.

.

.

.

.

In [ ]:
import io
raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
"""
df = pd.read_csv(io.StringIO(raw))

In [ ]:
# --- 1.1 ---
print(df.head())
print(df.tail(3))

In [ ]:
# --- 1.2 ---
print(df.columns)
print(df.index)
print(df.shape)
df.info()

In [ ]:
# --- 1.3 ---
df.describe().transpose()

In [ ]:
# --- 2.1 ---
df['Title']

In [ ]:
# --- 2.2 ---
df[['Title', 'Genre', 'Global_Sales']]

In [ ]:
# --- 2.3 ---
df['Sales_Ratio_NA'] = np.round(df['NA_Sales'] / df['Global_Sales'], 3)
df['Is_Nintendo'] = df['Publisher'] == 'Nintendo'
df.head()

In [ ]:
# --- 2.4 ---
df = df.drop('Sales_Ratio_NA', axis=1)
df.head()

In [ ]:
# --- 3.1 ---
df = df.set_index('Title')
df.head()

In [ ]:
# --- 3.2 ---
print(df.iloc[2])
print(df.loc['Minecraft'])

In [ ]:
# --- 3.3 ---
df.loc[['Halo 3', 'God of War']]

In [ ]:
# --- 3.4 ---
df = df.reset_index()
df.head()

In [ ]:
# --- 3.5 (Challenge) ---
df = df.set_index('Title')
df['EU_plus_JP'] = df['EU_Sales'] + df['JP_Sales']
result = df.loc[['Grand Theft Auto V', 'The Legend of Zelda'], ['Genre', 'Global_Sales', 'EU_plus_JP']]
print(result)
big_sellers = len(df[df['Global_Sales'] > 20])
print(f"\nGames with Global Sales > 20M: {big_sellers}")