# 🎮 Pandas Practice — 07: Text Methods
**Dataset:** Messy game titles and a reviews table. You'll clean, extract, and transform string data using pandas `.str` methods.

---
## Setup — run this cell first!

In [1]:
import pandas as pd
import numpy as np

# Game titles dataset — intentionally messy for cleaning exercises
raw_titles = pd.Series([
    "  grand theft auto v  ",
    "HALO 3",
    "minecraft",
    "  The   SIMS 3",
    "mario;kart;wii",
    "FIFA14",
    "god_of_war",
    "FINAL fantasy VII  ",
    "  resident evil 4",
    "pac man"
])

# Game reviews dataset
reviews = pd.DataFrame({
    'game':    ['Halo 3', 'GTA V', 'Minecraft', 'FIFA 14', 'God of War'],
    'review':  [
        'Great shooter - highly recommended for Xbox fans!',
        'Open world ACTION game, best of 2013... must buy.',
        'Simple yet DEEP. Perfect for all ages: kids and adults.',
        'Solid sports title; good graphics, weak career mode.',
        'EPIC action-adventure. A masterpiece -- truly.'
    ],
    'tags': [
        'shooter|action|xbox',
        'action|open-world|rockstar',
        'sandbox|survival|indie',
        'sports|football|ea',
        'action|adventure|sony'
    ],
    'score': ['9/10', '9.5/10', '8/10', '7/10', '10/10']
})

print("raw_titles loaded:", len(raw_titles), "entries")
print("reviews loaded:", reviews.shape)

raw_titles loaded: 10 entries
reviews loaded: (5, 4)

---
## Section 1 — Basic `.str` methods

### Exercise 1.1
Using `raw_titles`, apply `.str.strip()` to remove leading/trailing spaces.
Then apply `.str.title()` to capitalize properly. Chain both in one line.

In [ ]:
# Your code here

### Exercise 1.2
On `raw_titles`, use `.str.upper()` and `.str.lower()` separately.
Then use `.str.len()` to get the character count of each title (before cleaning).

In [ ]:
# Your code here
raw_titles.str.upper()

In [ ]:
raw_titles.str.lower()

In [ ]:
raw_titles.str.len()

### Exercise 1.3
Use `.str.contains()` to find all titles in `raw_titles` that contain the word `'mario'` (case-insensitive).
*(Hint: use the `case=False` parameter)*

In [ ]:
# Your code here
raw_titles.str.contains('mario', case=False)

### Exercise 1.4
Use `.str.startswith()` to find titles that start with a space character `' '`.
How many have leading spaces?

In [15]:
# Your code here
raw_titles.str.startswith('')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

### Exercise 1.5
Use `.str.replace()` to:
1. Replace all `;` with a space in `raw_titles`
2. Replace all `_` with a space in `raw_titles`
Chain both in one line.

In [ ]:
# Your code here
display(raw_titles)
display(raw_titles.str.replace(';',' ').str.replace('_',' '))

---
## Section 2 — Splitting, Grabbing, and Expanding

### Exercise 2.1
In the `reviews` DataFrame, split the `tags` column on `'|'`.
What type does each cell become?

In [ ]:
# Your code here
print(reviews)
print(reviews['tags'].str.split('|', expand =True))

### Exercise 2.2
Split the `tags` column on `'|'` and use `expand=True` to turn it into separate columns.
Save the result as `tags_df` and display it.

In [27]:
# Your code here
tags_df = reviews['tags'].str.split('|', expand=True)
display(tags_df)

         0           1         2
0  shooter      action      xbox
1   action  open-world  rockstar
2  sandbox    survival     indie
3   sports    football        ea
4   action   adventure      sony

### Exercise 2.3
From `tags_df`, extract only the **first tag** (column 0) for each game.
Add it as a new column `'primary_tag'` to the `reviews` DataFrame.

In [31]:
# Your code here
reviews['primary_tag']= tags_df[0]
reviews

,game,review,tags,score,primary_tag
0,Halo 3,Great shooter - highly recommended for Xbox fans!,shooter|action|xbox,9/10,shooter
1,GTA V,"Open world ACTION game, best of 2013... must buy.",action|open-world|rockstar,9.5/10,action
2,Minecraft,Simple yet DEEP. Perfect for all ages: kids an...,sandbox|survival|indie,8/10,sandbox
3,FIFA 14,"Solid sports title; good graphics, weak career...",sports|football|ea,7/10,sports
4,God of War,EPIC action-adventure. A masterpiece -- truly.,action|adventure|sony,10/10,action

### Exercise 2.4
Split the `score` column (e.g. `'9/10'`) on `'/'` and extract just the **numeric score** as a new column `'score_num'`.
Convert it to a float.

In [39]:
# Your code here
score_n = reviews['score'].str.split('/').str[0].astype(float)

---
## Section 3 — Cleaning pipeline

### Exercise 3.1
Build a full cleaning pipeline for `raw_titles` in a single chained expression:
1. Strip whitespace
2. Replace `;` with space
3. Replace `_` with space
4. Apply `.title()` capitalization

Save the result as `clean_titles`.

In [ ]:
# Your code here
clean_titles = raw_titles.str.strip().str.replace(';',' ').str.replace('_',' ').str.title()
display(raw_titles)
display(clean_titles)

### Exercise 3.2
Replicate the same pipeline using a custom `cleanup()` function + `np.vectorize()`.
Time both approaches with `%%timeit` (one cell each) and note which is faster.
*(This is a real-world skill — vectorize wins on large datasets)*

In [ ]:
def cleanup(title):
    title = title.strip()
    title = title.replace(';', ' ')
    title = title.replace('_', ' ')
    title = title.title()
    return title

In [41]:
# Time the .str chain approach
%%timeit
print(raw_titles.str.strip().str.replace(';',' ').str.replace('_',' ').str.title().values)

UsageError: Line magic function `%%timeit` not found.

In [ ]:
# Time the np.vectorize approach
# %%timeit
print(np.vectorize(cleanup)(raw_titles).tolist())

---
## Section 4 — Text analysis on the reviews column

### Exercise 4.1
Count how many reviews contain the word `'action'` (case-insensitive).

In [56]:
# Your code here
reviews['review'].str.contains('action', case=False).sum()

np.int64(2)

### Exercise 4.2
Create a new column `'word_count'` in `reviews` by splitting each review on spaces
and counting the resulting words.

In [63]:
# Your code here
reviews['word_count']= reviews['review'].str.split().str.len()
reviews

,game,review,tags,score,primary_tag,word_count
0,Halo 3,Great shooter - highly recommended for Xbox fans!,shooter|action|xbox,9/10,shooter,8
1,GTA V,"Open world ACTION game, best of 2013... must buy.",action|open-world|rockstar,9.5/10,action,9
2,Minecraft,Simple yet DEEP. Perfect for all ages: kids an...,sandbox|survival|indie,8/10,sandbox,10
3,FIFA 14,"Solid sports title; good graphics, weak career...",sports|football|ea,7/10,sports,8
4,God of War,EPIC action-adventure. A masterpiece -- truly.,action|adventure|sony,10/10,action,6

### Exercise 4.3
Extract everything before the first punctuation mark (`-`, `.`, `,`, `;`, `:`  or `--`)
from the `review` column using `.str.split()` with a regex pattern.
*(Hint: `r'[-.,;:]+|--'`)*
Store in a column `'first_phrase'`.

In [67]:
# Your code here
first_phrase = reviews['review'].str.split(r'[-.,;:]+|--').str[0].str.strip()
first_phrase

0             Great shooter
1    Open world ACTION game
2           Simple yet DEEP
3        Solid sports title
4               EPIC action
Name: review, dtype: object

---
## 🔥 Final Challenge

You receive this raw Series of game entries from a scraped webpage:
```python
scraped = pd.Series([
    "  grand theft AUTO v  | action | 2013 | take-two  ",
    "HALO 3|shooter|2007|microsoft",
    " minecraft | sandbox | 2013 | mojang ",
    "FIFA 14|sports|2013|EA Sports",
    "  GOD OF WAR | action-adventure | 2005 | sony  "
])
```

**Step 1:** Split each entry on `'|'` with `expand=True` into 4 columns: `title`, `genre`, `year`, `publisher`.

**Step 2:** Strip whitespace from all 4 columns.

**Step 3:** Apply `.str.title()` to `title` and `publisher`. Apply `.str.lower()` to `genre`.

**Step 4:** Convert `year` to integer.

**Step 5:** Add a column `'title_length'` = number of characters in the cleaned title.

**Step 6:** Filter and show only games where `genre` contains `'action'`.

In [86]:
scraped = pd.Series([
    '  grand theft AUTO v  | action | 2013 | take-two  ',
    'HALO 3|shooter|2007|microsoft',
    ' minecraft | sandbox | 2013 | mojang ',
    'FIFA 14|sports|2013|EA Sports',
    '  GOD OF WAR | action-adventure | 2005 | sony  '
])
# Step 1
clean = scraped.str.split('|', expand = True)
clean.columns=['title', 'genre','year','publisher']
clean

                    title               genre    year    publisher
0    grand theft AUTO v               action    2013    take-two
1                  HALO 3             shooter    2007    microsoft
2              minecraft             sandbox    2013       mojang
3                 FIFA 14              sports    2013    EA Sports
4             GOD OF WAR    action-adventure    2005        sony

In [87]:
# Step 2
for col in clean:
    clean[col] = clean[col].str.strip()
clean

                title             genre  year  publisher
0  grand theft AUTO v            action  2013   take-two
1              HALO 3           shooter  2007  microsoft
2           minecraft           sandbox  2013     mojang
3             FIFA 14            sports  2013  EA Sports
4          GOD OF WAR  action-adventure  2005       sony

In [88]:
# Step 3
clean['title'] = clean['title'].str.title()
clean['publisher'] = clean['publisher'].str.title()
clean['genre'] = clean['genre'].str.lower()
clean

                title             genre  year  publisher
0  Grand Theft Auto V            action  2013   Take-Two
1              Halo 3           shooter  2007  Microsoft
2           Minecraft           sandbox  2013     Mojang
3             Fifa 14            sports  2013  Ea Sports
4          God Of War  action-adventure  2005       Sony

In [89]:
# Step 4
clean['year'] = clean['year'].astype(int)
clean

                title             genre  year  publisher
0  Grand Theft Auto V            action  2013   Take-Two
1              Halo 3           shooter  2007  Microsoft
2           Minecraft           sandbox  2013     Mojang
3             Fifa 14            sports  2013  Ea Sports
4          God Of War  action-adventure  2005       Sony

In [90]:
# Step 5
clean['title_lenght'] = clean['title'].str.len()
clean

                title             genre  year  publisher  title_lenght
0  Grand Theft Auto V            action  2013   Take-Two            18
1              Halo 3           shooter  2007  Microsoft             6
2           Minecraft           sandbox  2013     Mojang             9
3             Fifa 14            sports  2013  Ea Sports             7
4          God Of War  action-adventure  2005       Sony            10

In [91]:
# Step 6
clean[clean['genre'].str.contains('action')]

                title             genre  year publisher  title_lenght
0  Grand Theft Auto V            action  2013  Take-Two            18
4          God Of War  action-adventure  2005      Sony            10