# 🎮 Pandas Practice — 04: Missing Data
**Dataset:** Video game global sales (mini VGChartz).
`Critic_Score` and `User_Score` have intentional gaps — perfect for practicing missing-data techniques.

---
## Setup — run this cell first!

In [1]:
import numpy as np
import pandas as pd
import io

raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
Resident Evil 4,Action,PS2,2005,Capcom,2.0,1.91,1.06,5.97,96,8.9
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92,9.0
"""
df = pd.read_csv(io.StringIO(raw))
print("Dataset loaded! Shape:", df.shape)
df.head()

Dataset loaded! Shape: (25, 11)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN

---
## Section 1 — Detecting Missing Data

### Exercise 1.1
Call `.isnull()` on the full DataFrame. How many missing values exist **per column**?
*(Hint: chain `.sum()` after `.isnull()`)*

In [4]:
# Your code here
df.isnull().sum()

Title           0
Genre           0
Platform        0
Year            0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Global_Sales    0
Critic_Score    7
User_Score      8
dtype: int64

### Exercise 1.2
What **percentage** of values are missing per column? Round to 1 decimal.
*(Hint: divide `.isnull().sum()` by `len(df)` and multiply by 100)*

In [6]:
# Your code here
((df.isnull().sum()/len(df))*100).round(1)

Title            0.0
Genre            0.0
Platform         0.0
Year             0.0
Publisher        0.0
NA_Sales         0.0
EU_Sales         0.0
JP_Sales         0.0
Global_Sales     0.0
Critic_Score    28.0
User_Score      32.0
dtype: float64

### Exercise 1.3
Filter and display only the rows where **both** `Critic_Score` AND `User_Score` are missing.

In [7]:
# Your code here
df[df['Critic_Score'].isnull() & df['User_Score'].isnull()]

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN

### Exercise 1.4
Filter the rows where `Critic_Score` is missing but `User_Score` is **not** missing.
How many rows match?

In [9]:
# Your code here
results = df[df['Critic_Score'].isnull() & df['User_Score'].notnull()]
print(f"Rows matching: {len(results)}")

Rows matching: 0

---
## Section 2 — Dropping Missing Data

### Exercise 2.1
Drop all rows that have **any** NaN value. How many rows remain?
*(Don't save to `df` — just display the result)*

In [10]:
# Your code here
df.dropna()
len(df)

25

### Exercise 2.2
Drop rows using `thresh=`: keep only rows that have **at least 9 non-null values**.
How many rows does this keep vs. the default `dropna()`?

In [ ]:
# Your code here
results = df.dropna(thresh = 9)
print(f"Rows matching: {len(results)}")

thresh=9 keeps: 25 rows
default dropna keeps: 17 rows

### Exercise 2.3
Drop **columns** that have any NaN values (`axis=1`).
Which columns are removed?

In [19]:
# Your code here
before = set(df.columns)
after = set (df.dropna(axis=1).columns)
print(f"Columns removed: {before-after}")

Columns removed: {'Critic_Score', 'User_Score'}

### Exercise 2.4
Drop columns where **more than 10%** of values are missing.
*(Hint: use `thresh=` with `axis=1`. `thresh` expects a minimum number of non-null values.)*

In [22]:
# Your code here
results = df.dropna(thresh = int(len(df)*0.9), axis = 1)
results

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16
24,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72

---
## Section 3 — Filling Missing Data

### Exercise 3.1
Fill missing values in `Critic_Score` with the **mean** of that column. Round to 1 decimal.
Save the result back to `df['Critic_Score']` and confirm there are no more NaNs in it.

In [23]:
# Your code here
df['Critic_Score'] = df['Critic_Score'].fillna(df['Critic_Score'].mean())
df

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.000000,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,86.666667,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.000000,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.000000,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,86.666667,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,86.666667,NaN
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.000000,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.000000,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.000000,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,86.666667,NaN
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.000000,7.5
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.000000,6.7
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.000000,8.2
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,86.666667,NaN
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.000000,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.000000,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.000000,7.9
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.000000,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,86.666667,NaN
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,86.666667,NaN
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.000000,NaN
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.000000,8.7
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.000000,8.9
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.000000,8.2
24,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.000000,9.0

### Exercise 3.2
Fill missing values in `User_Score` with the **median** of that column.
Why might median be a better choice than mean here?
*(Write your reasoning as a comment in the code cell)*

In [24]:
# Your code here
df['User_Score'] = df['User_Score'].fillna(df['User_Score'].median())
df

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.000000,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,86.666667,8.2
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.000000,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.000000,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,86.666667,8.2
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,86.666667,8.2
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.000000,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.000000,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.000000,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,86.666667,8.2
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.000000,7.5
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.000000,6.7
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.000000,8.2
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,86.666667,8.2
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.000000,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.000000,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.000000,7.9
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.000000,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,86.666667,8.2
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,86.666667,8.2
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.000000,8.2
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.000000,8.7
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.000000,8.9
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.000000,8.2
24,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.000000,9.0

### Exercise 3.3
Fill all remaining NaN values in the full DataFrame with the string `'Unknown'`.
*(Don't save to `df` — just display)*

In [25]:
# Your code here
df.fillna('Unknown')
df

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.000000,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,86.666667,8.2
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.000000,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.000000,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,86.666667,8.2
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,86.666667,8.2
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.000000,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.000000,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.000000,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,86.666667,8.2
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.000000,7.5
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.000000,6.7
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.000000,8.2
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,86.666667,8.2
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.000000,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.000000,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.000000,7.9
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.000000,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,86.666667,8.2
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,86.666667,8.2
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.000000,8.2
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.000000,8.7
22,Resident Evil 4,Action,PS2,2005,Capcom,2.00,1.91,1.06,5.97,96.000000,8.9
23,Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95.000000,8.2
24,Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92.000000,9.0

---
## Section 4 — Interpolation

### Exercise 4.1
You have a Series of monthly active users (in millions) with a gap:
```python
mau = pd.Series([12.0, 13.5, np.nan, np.nan, 17.0, 18.5], index=['Jan','Feb','Mar','Apr','May','Jun'])
```
1. Display the Series.
2. Fill the gaps using **linear interpolation**.
3. Fill the gaps using **polynomial interpolation** (`order=2`).
4. Which result makes more sense for this data? Write your answer as a comment.

In [34]:
mau = pd.Series([12.0, 13.5, np.nan, np.nan, 17.0, 18.5], index=['Jan','Feb','Mar','Apr','May','Jun'])
display(mau)
mau.interpolate()

Jan    12.0
Feb    13.5
Mar     NaN
Apr     NaN
May    17.0
Jun    18.5
dtype: float64

Jan    12.000000
Feb    13.500000
Mar    14.666667
Apr    15.833333
May    17.000000
Jun    18.500000
dtype: float64

### Exercise 4.2
You have a DataFrame of ticket prices with a missing tier:
```python
tix = pd.DataFrame({'Price': [200, np.nan, 80, 40]}, index=['VIP','Premium','Standard','Economy'])
```
Interpolate the missing price. Does linear interpolation give a realistic estimate here?
Write your answer as a comment.

In [36]:
tix = pd.DataFrame({'Price': [200, np.nan, 80, 40]}, index=['VIP','Premium','Standard','Economy'])
# Your code here
tix.interpolate()

          Price
VIP       200.0
Premium   140.0
Standard   80.0
Economy    40.0

---
## 🔥 Final Challenge

You receive a new, messier version of the dataset with more missing values:

In [37]:
messy_raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
,,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,,2008,,15.85,12.88,3.79,35.82,82,8.9
,Sports,Wii,2009,Nintendo,,,3.28,,80,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,,Nintendo,11.38,9.23,6.5,30.01,89,8.5
,Misc,Wii,2006,Nintendo,14.03,9.2,,29.02,58,6.6
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
,,,,,,,,,, 
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
"""
messy = pd.read_csv(io.StringIO(messy_raw))
messy

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006.0,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,NaN,NaN,NES,1985.0,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,NaN,2008.0,NaN,15.85,12.88,3.79,35.82,82.0,8.9
3,NaN,Sports,Wii,2009.0,Nintendo,NaN,NaN,3.28,NaN,80.0,NaN
4,Tetris,Puzzle,GB,1989.0,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
5,New Super Mario Bros,Platform,DS,NaN,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5
6,NaN,Misc,Wii,2006.0,Nintendo,14.03,9.20,NaN,29.02,58.0,6.6
7,Grand Theft Auto V,Action,PS3,2013.0,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
9,Halo 3,Shooter,X360,2007.0,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3

**Step 1:** Count total missing values per column.

**Step 2:** Drop the row that is **completely empty** (all NaN). *(Hint: `thresh=1` keeps rows with at least 1 non-null)*

**Step 3:** Drop columns where more than 40% of values are missing.

**Step 4:** Fill missing `Critic_Score` with the mean. Fill missing `Publisher` with `'Unknown'`.

**Step 5:** How many rows still have **any** NaN after steps 2–4? Which columns still have gaps?

In [ ]:
# Step 1
print(messy.isnull().sum())

In [45]:
# Step 2
messy.dropna(thresh=1)
messy.shape

(10, 11)

In [50]:
# Step 3
percent = int(len(messy.columns)*0.6)
messy.dropna(thresh = percent ,axis = 1)
print(f"Columns remaining: {list(messy.columns)}")

Columns remaining: ['Title', 'Genre', 'Platform', 'Year', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales', 'Critic_Score', 'User_Score']

In [52]:
# Step 4
messy['Critic_Score'] = messy['Critic_Score'].fillna(messy['Critic_Score'].mean())
messy['Publisher'] = messy['Publisher'].fillna('Unknown')
messy

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006.0,Nintendo,41.49,29.02,3.77,82.74,76.000000,8.0
1,NaN,NaN,NES,1985.0,Nintendo,29.08,3.58,6.81,40.24,82.285714,NaN
2,Mario Kart Wii,Racing,NaN,2008.0,Unknown,15.85,12.88,3.79,35.82,82.000000,8.9
3,NaN,Sports,Wii,2009.0,Nintendo,NaN,NaN,3.28,NaN,80.000000,NaN
4,Tetris,Puzzle,GB,1989.0,Nintendo,23.20,2.26,4.22,30.26,82.285714,NaN
5,New Super Mario Bros,Platform,DS,NaN,Nintendo,11.38,9.23,6.50,30.01,89.000000,8.5
6,NaN,Misc,Wii,2006.0,Nintendo,14.03,9.20,NaN,29.02,58.000000,6.6
7,Grand Theft Auto V,Action,PS3,2013.0,Take-Two Interactive,7.01,9.27,0.97,20.32,97.000000,8.2
8,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,82.285714,
9,Halo 3,Shooter,X360,2007.0,Microsoft,7.22,3.93,0.08,12.32,94.000000,8.3

In [57]:
# Step 5
still = messy.isnull().sum()
print(f"Rows with any NaN: {messy.isnull().any(axis=1).sum()}")
print("Columns still with gaps:")
print(still[still > 0])

Rows with any NaN: 7
Columns still with gaps:
Title           4
Genre           2
Platform        2
Year            2
NA_Sales        2
EU_Sales        2
JP_Sales        2
Global_Sales    2
User_Score      3
dtype: int64