# 🎮 Pandas Practice — 05: Groupby & MultiIndex
**Dataset:** Video game global sales. You'll group, aggregate, and navigate hierarchical indexes.

---
## Setup — run this cell first!

In [1]:
import numpy as np
import pandas as pd
import io

raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
Resident Evil 4,Action,PS2,2005,Capcom,2.0,1.91,1.06,5.97,96,8.9
Halo 2,Shooter,XB,2004,Microsoft,8.49,2.51,0.05,11.16,95,8.2
Final Fantasy VII,Role-Playing,PS,1997,Square,3.01,6.06,3.28,9.72,92,9.0
"""
df = pd.read_csv(io.StringIO(raw))
print("Dataset loaded! Shape:", df.shape)
df.head()

Dataset loaded! Shape: (25, 11)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN

---
## Section 1 — Basic `groupby()`

### Exercise 1.1
Group by `Genre` and calculate the **mean** of all numeric columns.
Which genre has the highest average `Global_Sales`?

In [19]:
# Your code here
group_genre = df.groupby('Genre').mean(numeric_only = True)
print(f"Highest Average : {group_genre['Global_Sales'].idxmax()}")

Highest Average : Sports

### Exercise 1.2
Group by `Publisher` and get the **sum** of `NA_Sales`, `EU_Sales`, `JP_Sales`, and `Global_Sales`.
Sort by `Global_Sales` descending. Who dominates?

In [28]:
# Your code here
group_publisher = df.groupby('Publisher').sum()[['NA_Sales','EU_Sales','JP_Sales','Global_Sales']].sort_values('Global_Sales', ascending = False)
print(f"Publisher that dominates: {group_publisher['Global_Sales'].idxmax()}")

Publisher that dominates: Nintendo

### Exercise 1.3
Group by `Platform` and use `.describe()` on `Global_Sales`.
Transpose the result. Which platform has the highest `max`?

In [36]:
# Your code here
group_plat = df.groupby('Platform').describe()['Global_Sales'].transpose()
print(f"Platform with highest max: {group_plat.loc['max'].idxmax()}")

Platform with highest max: Wii

### Exercise 1.4
Use `.size()` (not `.count()`) to find how many games are in the dataset per `Genre`.
What is the difference between `.size()` and `.count()` in a groupby context?
*(Write your answer as a comment)*

In [ ]:
# Your code here
df.groupby('Genre').size()
#Count counts items on each column, size counts items per category

Genre
Action          4
Fighting        1
Misc            2
Platform        4
Puzzle          2
Racing          2
Role-Playing    2
Shooter         4
Simulation      1
Sports          3
dtype: int64

---
## Section 2 — Groupby multiple columns

### Exercise 2.1
Group by `['Genre', 'Publisher']` and compute the **mean** `Global_Sales`.
Save to a variable called `genre_pub`.

In [45]:
# Your code here
genre_pub = df.groupby(['Genre','Publisher']).mean(numeric_only = True)[['Global_Sales']]
genre_pub

                                   Global_Sales
Genre        Publisher
Action       Capcom                      5.9700
             Nintendo                    7.8000
             Sony                        5.1700
             Take-Two Interactive       20.3200
Fighting     Capcom                     11.9200
Misc         Microsoft                  13.0000
             Nintendo                   29.0200
Platform     Nintendo                   26.8625
Puzzle       Atari                       9.2800
             Nintendo                   30.2600
Racing       Nintendo                   35.8200
             Sony                       14.9800
Role-Playing Nintendo                   31.3700
             Square                      9.7200
Shooter      Activision                 20.5200
             Microsoft                  11.7400
             Nintendo                   28.3100
Simulation   EA                         10.2000
Sports       EA Sports                  12.2000
             Nintendo                   57.8700

### Exercise 2.2
Using `genre_pub`, inspect its index. Print:
- `.index` (the MultiIndex object)
- `.index.levels`
- `.index.names`

In [50]:
# Your code here
genre_pub.index
genre_pub.index.levels
genre_pub.index.names

FrozenList(['Genre', 'Publisher'])

---
## Section 3 — Indexing a MultiIndex

### Exercise 3.1
Using `genre_pub`, retrieve all rows where the outer index (Genre) is `'Action'`
using `.loc[]`.

In [49]:
# Your code here
genre_pub.loc['Action']

                      Global_Sales
Publisher
Capcom                        5.97
Nintendo                      7.80
Sony                          5.17
Take-Two Interactive         20.32

### Exercise 3.2
Retrieve the single row for Genre = `'Shooter'` and Publisher = `'Activision'`
using a tuple in `.loc[]`.

In [51]:
# Your code here
genre_pub.loc[('Shooter','Activision')]

Global_Sales    20.52
Name: (Shooter, Activision), dtype: float64

### Exercise 3.3
Use `.xs()` to retrieve all genres for Publisher = `'Nintendo'`
*(Hint: use `level='Publisher'`)*

In [54]:
# Your code here
genre_pub.xs(key='Nintendo', level='Publisher')

              Global_Sales
Genre
Action              7.8000
Misc               29.0200
Platform           26.8625
Puzzle             30.2600
Racing             35.8200
Role-Playing       31.3700
Shooter            28.3100
Sports             57.8700

### Exercise 3.4
Swap the index levels so `Publisher` becomes the outer level and `Genre` the inner.
Then sort the new index. Save to `pub_genre`.

In [56]:
# Your code here
pub_genre = genre_pub.swaplevel().sort_index()
pub_genre

                                   Global_Sales
Publisher            Genre
Activision           Shooter            20.5200
Atari                Puzzle              9.2800
Capcom               Action              5.9700
                     Fighting           11.9200
EA                   Simulation         10.2000
EA Sports            Sports             12.2000
Microsoft            Misc               13.0000
                     Shooter            11.7400
Nintendo             Action              7.8000
                     Misc               29.0200
                     Platform           26.8625
                     Puzzle             30.2600
                     Racing             35.8200
                     Role-Playing       31.3700
                     Shooter            28.3100
                     Sports             57.8700
Sony                 Action              5.1700
                     Racing             14.9800
Square               Role-Playing        9.7200
Take-Two Interactive Action             20.3200

---
## Section 4 — `agg()` for custom aggregations

### Exercise 4.1
On the full `df`, use `.agg()` to compute `['mean', 'median', 'std']` for the entire DataFrame.
Display only the columns `Global_Sales`, `NA_Sales`, `EU_Sales`.

In [63]:
# Your code here
df[['Global_Sales','NA_Sales','EU_Sales']].agg(['mean','median','std'])

        Global_Sales   NA_Sales  EU_Sales
mean       21.701200  11.753600  6.115200
median     14.980000   7.810000  4.730000
std        16.586694   9.649978  5.930226

### Exercise 4.2
Use `.agg()` with a dictionary to compute:
- `Global_Sales`: mean and max
- `Critic_Score`: median and min
- `NA_Sales`: sum and mean

In [65]:
# Your code here
df.agg({
    'Global_Sales':['mean','max'],
    'Critic_Score':['median','min'],
    'NA_Sales':['sum','mean']
    })

        Global_Sales  Critic_Score  NA_Sales
mean         21.7012           NaN   11.7536
max          82.7400           NaN       NaN
median           NaN          87.0       NaN
min              NaN          58.0       NaN
sum              NaN           NaN  293.8400

### Exercise 4.3 — `groupby` + `agg()`
Group by `Genre` and aggregate:
- `Global_Sales`: mean and sum
- `Critic_Score`: median (ignore NaN)
- `NA_Sales`: mean

Sort the result by `('Global_Sales', 'mean')` descending.

In [66]:
# Your code here
result = df.groupby('Genre').agg({
    'Global_Sales': ['mean', 'sum'],
    'Critic_Score' : ['median'],
    'NA_Sales': ['mean']   
})
result

             Global_Sales         Critic_Score NA_Sales
                     mean     sum       median     mean
Genre
Action           9.815000   39.26         96.0   4.5200
Fighting        11.920000   11.92          NaN   6.3000
Misc            21.010000   42.02         70.0  10.6450
Platform        26.862500  107.45         87.0  14.8525
Puzzle          19.770000   39.54          NaN  15.5050
Racing          25.400000   50.80         88.5  11.3500
Role-Playing    20.545000   41.09         92.0   7.1400
Shooter         18.077500   72.31         94.0  14.3400
Simulation      10.200000   10.20         86.0   4.1300
Sports          42.646667  127.94         80.0  19.7600

---
## Section 5 — Filter before groupby (good practice)

### Exercise 5.1
The course warns: *it's much easier to filter before groupby than after.*
Group only `'Action'` and `'Shooter'` games by `Publisher` and compute total `Global_Sales`.
Filter **before** the groupby call.

In [71]:
# Your code here
df[df['Genre'].isin(['Action','Shooter'])].groupby('Publisher')['Global_Sales'].sum()

Publisher
Activision              20.52
Capcom                   5.97
Microsoft               23.48
Nintendo                36.11
Sony                     5.17
Take-Two Interactive    20.32
Name: Global_Sales, dtype: float64

### Exercise 5.2
Among games released **after 2000**, group by `Genre` and get the mean `Critic_Score`.
Sort descending. Drop NaN groups.

In [78]:
# Your code here
df[df['Year'] > 2000].groupby('Genre')['Critic_Score'].mean().sort_values(ascending = False)

Genre
Action        95.666667
Shooter       92.000000
Racing        88.500000
Platform      88.000000
Simulation    86.000000
Sports        80.333333
Misc          70.000000
Name: Critic_Score, dtype: float64

---
## 🔥 Final Challenge

You're building a **genre performance dashboard**. Complete all steps:

**Step 1:** Group by `['Genre', 'Platform']` and compute mean `Global_Sales`. Save as `gp`.

**Step 2:** Use `.xs()` to extract all platforms for the `'Shooter'` genre.

**Step 3:** On `gp`, use `sort_index(level='Platform')` to sort by the inner level.

**Step 4:** Using `groupby` + `agg()` on the original `df`, create a summary table with:
  - `Global_Sales`: mean, sum, max
  - `Critic_Score`: median
  - grouped by `Genre`
  
**Step 5:** From that summary, which genre has the highest **total** (`sum`) Global_Sales?
Print just that genre name and its total.

In [ ]:
# Step 1
gp = df.groupby(['Genre','Platform'])['Global_Sales'].mean()
gp

In [ ]:
# Step 2
gp.xs(key='Shooter', level='Genre')

In [ ]:
# Step 3
gp.sort_index(level='Platform')

In [ ]:
# Step 4
group_genre = df.groupby('Genre').agg({
    'Global_Sales':['mean','sum','max'],
    'Critic_Score':['median']
})
group_genre

In [86]:
# Step 5
print(f"Highest total sum: {group_genre['Global_Sales'].idxmax()}")

Highest total sum: Sports