# 🎮 Pandas Practice — 02: Conditional Filtering
**Dataset:** Same video game sales dataset. Now you'll filter it like a real analyst.

---
## Setup — run this cell first!

In [10]:
import numpy as np
import pandas as pd
import io
from IPython.display import display, Markdown


raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
"""
df = pd.read_csv(io.StringIO(raw))
print("Dataset loaded! Shape:", df.shape)
df.head()

Dataset loaded! Shape: (22, 11)

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN

## Section 1 — Single Conditions

### Exercise 1.1
Filter all games where `Global_Sales` is greater than **20 million**.

In [ ]:
# Your code herep
display(Markdown("### Sales over 20 million"))
display(df[df['Global_Sales'] > 20])

### Juegos después de 2005

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2

### Exercise 1.2
Filter all games published by `'Nintendo'`.

In [20]:
# Your code here
display(Markdown("### Nintendo Games:"))
display(df[df['Publisher'] == 'Nintendo'])

### Nintendo Games:

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
0,Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76.0,8.0
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
3,Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.00,80.0,8.8
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN

### Exercise 1.3
Filter all games where the `Genre` is **NOT** `'Sports'`. Use the `~` operator.

In [21]:
# Your code here
display(Markdown("### No sports games:"))
display(df[df['Genre'] != 'Sports'])

### No sports games:

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
2,Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82.0,8.9
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5
7,Wii Play,Misc,Wii,2006,Nintendo,14.03,9.20,2.93,29.02,58.0,6.6
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7

## Section 2 — Multiple Conditions

### Exercise 2.1 — AND condition
Filter games that are:
- Genre is `'Shooter'` **AND**
- `NA_Sales` is greater than 7

In [22]:
# Your code here
display(Markdown("### Shooter and Sales over 7 Games:"))
display(df[ (df['Genre'] == 'Shooter') & (df['NA_Sales'] > 7) ])

### Shooter and Sales over 7 Games:

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3

### Exercise 2.2 — OR condition
Filter games released in `1985` **OR** `1989`.

In [23]:
# Your code here
display(Markdown("### Games releades on 1985 or 1989:"))
display(df[df['Year'].isin([1985,1989])])

### Games releades on 1985 or 1989:

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN

### Exercise 2.3 — Combining AND + NOT
Filter games where:
- `Global_Sales` > 10 million **AND**
- Publisher is **NOT** `'Nintendo'`

In [24]:
# Your code here
display(Markdown("### Sales over 10 and publisher NOT nintendo"))
display(df[(df['Global_Sales'] > 10) & (df['Publisher'] != 'Nintendo')])

### Sales over 10 and publisher NOT nintendo

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.0,6.7
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN

### Exercise 2.4 — Three conditions
Filter games where:
- `Genre` is `'Action'` **AND**
- `EU_Sales` > 5 **AND**
- `Critic_Score` > 90

How many results do you get?

In [26]:
# Your code here
display(Markdown("### Action, EU Sales over 5 and Critic Score over 90"))
conditions = (df['Genre'] == 'Action') & (df['EU_Sales'] > 5) & (df['Critic_Score'] > 90)
display(df[conditions])

### Action, EU Sales over 5 and Critic Score over 90

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2

## Section 3 — `.isin()`

### Exercise 3.1
Filter games where the `Platform` is in this list: `['PS2', 'PS3', 'X360']`.

In [27]:
# Your code here
list = ['PS2', 'PS3', 'X360']
display(df[df['Platform'].isin(list)])

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
11,FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.20,85.0,6.7
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2
14,Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95.0,8.2
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3
16,Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.00,82.0,7.9
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7

### Exercise 3.2 — NOT isin()
Filter games where the `Genre` is **NOT** in `['Sports', 'Racing', 'Misc']`.

In [34]:
# Your code here
list2 = ['Sports', 'Racing', 'Misc']
display(df[~df['Genre'].isin(list2)])

,Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
1,Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,NaN,NaN
4,Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,NaN,NaN
5,Tetris,Puzzle,GB,1989,Nintendo,23.20,2.26,4.22,30.26,NaN,NaN
6,New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.50,30.01,89.0,8.5
8,New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.70,28.62,87.0,8.4
9,Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,NaN,NaN
10,Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87.0,7.5
12,Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97.0,8.2
13,The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.00,1.07,7.80,NaN,NaN
15,Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94.0,8.3
17,The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.30,10.20,86.0,6.8
18,Street Fighter II,Fighting,SNES,1992,Capcom,6.30,1.88,3.08,11.92,NaN,NaN
19,Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,NaN,NaN
20,Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85.0,NaN
21,God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94.0,8.7

## 🔥 Challenge — Exercise 3.3
You're a market analyst. Answer these questions using conditional filtering:

1. **Question A:** Which games sold more than 5M in Europe (`EU_Sales > 5`) AND were released after 2005? Show only `Title`, `Genre`, `EU_Sales`, and `Year`.

2. **Question B:** How many unique genres exist among games that sold more than 15M globally?
*(Hint: filter first, then use `.nunique()` or `.unique()` on the Genre column)*

3. **Question C:** Filter all Nintendo games on handheld platforms (`['GB', 'DS', 'GBA']`). What is the total combined `Global_Sales` for this group?
*(Hint: filter, then use `.sum()` on the Global_Sales column)*

In [ ]:
# Question A
display(Markdown("### EU SALES over 5 AND released afte 2005"))
conditions1 = (df['EU_Sales'] > 5) & (df['Year'] > 2005)
display(df.loc[conditions1, ['Title', 'Genre', 'EU_Sales', 'Year']])

In [43]:
# Question B
display(Markdown("### Unique Genres with sells more than 15M"))
filter = df[df['Global_Sales'] > 15]
display(filter['Genre'].nunique())

### Unique Genres with sells more than 15M

8

In [47]:
# Question C
display(Markdown("### Nintendo on Handheld platforms"))
conditions2 = (df['Publisher'] == 'Nintendo') & (df['Platform'].isin(['GB', 'DS', 'GBA']))
display(df[conditions2]['Global_Sales'].sum())

### Nintendo on Handheld platforms

np.float64(91.64)

---
# 📋 SOLUTIONS
*(Scroll down only after attempting the exercises!)*

.

.

.

.

.

.

.

In [ ]:
import io
raw = """Title,Genre,Platform,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Global_Sales,Critic_Score,User_Score
Wii Sports,Sports,Wii,2006,Nintendo,41.49,29.02,3.77,82.74,76,8.0
Super Mario Bros,Platform,NES,1985,Nintendo,29.08,3.58,6.81,40.24,,,
Mario Kart Wii,Racing,Wii,2008,Nintendo,15.85,12.88,3.79,35.82,82,8.9
Wii Sports Resort,Sports,Wii,2009,Nintendo,15.75,11.01,3.28,33.0,80,8.8
Pokemon Red/Blue,Role-Playing,GB,1996,Nintendo,11.27,8.89,10.22,31.37,,
Tetris,Puzzle,GB,1989,Nintendo,23.2,2.26,4.22,30.26,,
New Super Mario Bros,Platform,DS,2006,Nintendo,11.38,9.23,6.5,30.01,89,8.5
Wii Play,Misc,Wii,2006,Nintendo,14.03,9.2,2.93,29.02,58,6.6
New Super Mario Bros Wii,Platform,Wii,2009,Nintendo,14.59,7.06,4.7,28.62,87,8.4
Duck Hunt,Shooter,NES,1984,Nintendo,26.93,0.63,0.28,28.31,,
Call of Duty Black Ops,Shooter,X360,2010,Activision,14.72,5.05,0.36,20.52,87,7.5
FIFA 14,Sports,PS3,2013,EA Sports,2.04,8.74,0.06,12.2,85,6.7
Grand Theft Auto V,Action,PS3,2013,Take-Two Interactive,7.01,9.27,0.97,20.32,97,8.2
The Legend of Zelda,Action,NES,1987,Nintendo,6.51,0.0,1.07,7.8,,
Gran Turismo 3,Racing,PS2,2001,Sony,6.85,5.09,1.87,14.98,95,8.2
Halo 3,Shooter,X360,2007,Microsoft,7.22,3.93,0.08,12.32,94,8.3
Minecraft,Misc,X360,2013,Microsoft,7.26,4.18,0.19,13.0,82,7.9
The Sims 3,Simulation,PC,2009,EA,4.13,4.73,0.3,10.2,86,6.8
Street Fighter II,Fighting,SNES,1992,Capcom,6.3,1.88,3.08,11.92,,
Pac-Man,Puzzle,Atari,1982,Atari,7.81,0.77,0.04,9.28,,
Donkey Kong Country,Platform,SNES,1994,Nintendo,4.36,2.88,0.83,8.58,85,
God of War,Action,PS2,2005,Sony,2.56,2.12,0.07,5.17,94,8.7
"""
df = pd.read_csv(io.StringIO(raw))

In [ ]:
# --- 1.1 ---
df[df['Global_Sales'] > 20]

In [ ]:
# --- 1.2 ---
df[df['Publisher'] == 'Nintendo']

In [ ]:
# --- 1.3 ---
df[~(df['Genre'] == 'Sports')]

In [ ]:
# --- 2.1 ---
df[(df['Genre'] == 'Shooter') & (df['NA_Sales'] > 7)]

In [ ]:
# --- 2.2 ---
df[(df['Year'] == 1985) | (df['Year'] == 1989)]

In [ ]:
# --- 2.3 ---
df[(df['Global_Sales'] > 10) & ~(df['Publisher'] == 'Nintendo')]

In [ ]:
# --- 2.4 ---
result = df[(df['Genre'] == 'Action') & (df['EU_Sales'] > 5) & (df['Critic_Score'] > 90)]
print(result)
print(f"\nCount: {len(result)}")

In [ ]:
# --- 3.1 ---
df[df['Platform'].isin(['PS2', 'PS3', 'X360'])]

In [ ]:
# --- 3.2 ---
df[~df['Genre'].isin(['Sports', 'Racing', 'Misc'])]

In [ ]:
# --- 3.3 A ---
filtered = df[(df['EU_Sales'] > 5) & (df['Year'] > 2005)]
filtered[['Title', 'Genre', 'EU_Sales', 'Year']]

In [ ]:
# --- 3.3 B ---
big_sellers = df[df['Global_Sales'] > 15]
print(f"Unique genres: {big_sellers['Genre'].nunique()}")
print(big_sellers['Genre'].unique())

In [ ]:
# --- 3.3 C ---
nintendo_handheld = df[(df['Publisher'] == 'Nintendo') & (df['Platform'].isin(['GB', 'DS', 'GBA']))]
total = nintendo_handheld['Global_Sales'].sum()
print(f"Total Global Sales: {total:.2f}M")